//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VotGESOrders.AdditService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/VotGESOrders.Web.Models")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AllowCreateCranTaskField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AllowCreateCrashOrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AllowCreateOrderField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AllowEditTreeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool AllowEditUsersField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int UserIDField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AllowCreateCranTask {
            get {
                return this.AllowCreateCranTaskField;
            }
            set {
                if ((this.AllowCreateCranTaskField.Equals(value) != true)) {
                    this.AllowCreateCranTaskField = value;
                    this.RaisePropertyChanged("AllowCreateCranTask");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AllowCreateCrashOrder {
            get {
                return this.AllowCreateCrashOrderField;
            }
            set {
                if ((this.AllowCreateCrashOrderField.Equals(value) != true)) {
                    this.AllowCreateCrashOrderField = value;
                    this.RaisePropertyChanged("AllowCreateCrashOrder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AllowCreateOrder {
            get {
                return this.AllowCreateOrderField;
            }
            set {
                if ((this.AllowCreateOrderField.Equals(value) != true)) {
                    this.AllowCreateOrderField = value;
                    this.RaisePropertyChanged("AllowCreateOrder");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AllowEditTree {
            get {
                return this.AllowEditTreeField;
            }
            set {
                if ((this.AllowEditTreeField.Equals(value) != true)) {
                    this.AllowEditTreeField = value;
                    this.RaisePropertyChanged("AllowEditTree");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool AllowEditUsers {
            get {
                return this.AllowEditUsersField;
            }
            set {
                if ((this.AllowEditUsersField.Equals(value) != true)) {
                    this.AllowEditUsersField = value;
                    this.RaisePropertyChanged("AllowEditUsers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FullName {
            get {
                return this.FullNameField;
            }
            set {
                if ((object.ReferenceEquals(this.FullNameField, value) != true)) {
                    this.FullNameField = value;
                    this.RaisePropertyChanged("FullName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int UserID {
            get {
                return this.UserIDField;
            }
            set {
                if ((this.UserIDField.Equals(value) != true)) {
                    this.UserIDField = value;
                    this.RaisePropertyChanged("UserID");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="AdditService.AdditService")]
    public interface AdditService {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:AdditService/DoWork", ReplyAction="urn:AdditService/DoWorkResponse")]
        void DoWork();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:AdditService/DoWork", ReplyAction="urn:AdditService/DoWorkResponse")]
        System.Threading.Tasks.Task DoWorkAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:AdditService/GetAuthenticatedUser", ReplyAction="urn:AdditService/GetAuthenticatedUserResponse")]
        VotGESOrders.AdditService.User GetAuthenticatedUser();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:AdditService/GetAuthenticatedUser", ReplyAction="urn:AdditService/GetAuthenticatedUserResponse")]
        System.Threading.Tasks.Task<VotGESOrders.AdditService.User> GetAuthenticatedUserAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:AdditService/info", ReplyAction="urn:AdditService/infoResponse")]
        void info(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:AdditService/info", ReplyAction="urn:AdditService/infoResponse")]
        System.Threading.Tasks.Task infoAsync(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:AdditService/error", ReplyAction="urn:AdditService/errorResponse")]
        void error(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:AdditService/error", ReplyAction="urn:AdditService/errorResponse")]
        System.Threading.Tasks.Task errorAsync(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:AdditService/debug", ReplyAction="urn:AdditService/debugResponse")]
        void debug(string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:AdditService/debug", ReplyAction="urn:AdditService/debugResponse")]
        System.Threading.Tasks.Task debugAsync(string message);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AdditServiceChannel : VotGESOrders.AdditService.AdditService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdditServiceClient : System.ServiceModel.ClientBase<VotGESOrders.AdditService.AdditService>, VotGESOrders.AdditService.AdditService {
        
        public AdditServiceClient() {
        }
        
        public AdditServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdditServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdditServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdditServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void DoWork() {
            base.Channel.DoWork();
        }
        
        public System.Threading.Tasks.Task DoWorkAsync() {
            return base.Channel.DoWorkAsync();
        }
        
        public VotGESOrders.AdditService.User GetAuthenticatedUser() {
            return base.Channel.GetAuthenticatedUser();
        }
        
        public System.Threading.Tasks.Task<VotGESOrders.AdditService.User> GetAuthenticatedUserAsync() {
            return base.Channel.GetAuthenticatedUserAsync();
        }
        
        public void info(string message) {
            base.Channel.info(message);
        }
        
        public System.Threading.Tasks.Task infoAsync(string message) {
            return base.Channel.infoAsync(message);
        }
        
        public void error(string message) {
            base.Channel.error(message);
        }
        
        public System.Threading.Tasks.Task errorAsync(string message) {
            return base.Channel.errorAsync(message);
        }
        
        public void debug(string message) {
            base.Channel.debug(message);
        }
        
        public System.Threading.Tasks.Task debugAsync(string message) {
            return base.Channel.debugAsync(message);
        }
    }
}
