//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 5.0.61118.0
// 
namespace VotGESOrders.CranService {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CranFilter", Namespace="http://schemas.datacontract.org/2004/07/VotGESOrders.Web.Models")]
    public partial class CranFilter : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Collections.ObjectModel.ObservableCollection<string> CranUsersField;
        
        private System.Collections.ObjectModel.ObservableCollection<VotGESOrders.CranService.CranTaskInfo> DataField;
        
        private System.DateTime DateEndField;
        
        private System.DateTime DateStartField;
        
        private System.Collections.ObjectModel.ObservableCollection<string> ManagersField;
        
        private System.Collections.ObjectModel.ObservableCollection<string> StropUsersField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<string> CranUsers {
            get {
                return this.CranUsersField;
            }
            set {
                if ((object.ReferenceEquals(this.CranUsersField, value) != true)) {
                    this.CranUsersField = value;
                    this.RaisePropertyChanged("CranUsers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<VotGESOrders.CranService.CranTaskInfo> Data {
            get {
                return this.DataField;
            }
            set {
                if ((object.ReferenceEquals(this.DataField, value) != true)) {
                    this.DataField = value;
                    this.RaisePropertyChanged("Data");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateEnd {
            get {
                return this.DateEndField;
            }
            set {
                if ((this.DateEndField.Equals(value) != true)) {
                    this.DateEndField = value;
                    this.RaisePropertyChanged("DateEnd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateStart {
            get {
                return this.DateStartField;
            }
            set {
                if ((this.DateStartField.Equals(value) != true)) {
                    this.DateStartField = value;
                    this.RaisePropertyChanged("DateStart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<string> Managers {
            get {
                return this.ManagersField;
            }
            set {
                if ((object.ReferenceEquals(this.ManagersField, value) != true)) {
                    this.ManagersField = value;
                    this.RaisePropertyChanged("Managers");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.ObjectModel.ObservableCollection<string> StropUsers {
            get {
                return this.StropUsersField;
            }
            set {
                if ((object.ReferenceEquals(this.StropUsersField, value) != true)) {
                    this.StropUsersField = value;
                    this.RaisePropertyChanged("StropUsers");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CranTaskInfo", Namespace="http://schemas.datacontract.org/2004/07/VotGESOrders.Web.Models")]
    public partial class CranTaskInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string AgreeCommentsField;
        
        private System.Collections.Generic.Dictionary<int, string> AgreeDictField;
        
        private System.DateTime AllowDateEndField;
        
        private System.DateTime AllowDateStartField;
        
        private bool AllowedField;
        
        private string AuthorField;
        
        private string AuthorAllowField;
        
        private string AuthorCancelField;
        
        private string AuthorFinishField;
        
        private string AuthorOpenField;
        
        private string AuthorTextField;
        
        private bool CancelledField;
        
        private string CommentField;
        
        private string CranNameField;
        
        private int CranNumberField;
        
        private string CranUserField;
        
        private string CranUserShortField;
        
        private System.DateTime DateCreateField;
        
        private bool DeniedField;
        
        private bool FinishCurrentTimeField;
        
        private bool FinishedField;
        
        private bool HasAgreeCommentField;
        
        private bool HasReviewCommentField;
        
        private string ManagerField;
        
        private string ManagerShortField;
        
        private System.DateTime NeedEndDateField;
        
        private System.DateTime NeedStartDateField;
        
        private int NumberField;
        
        private bool OpenCurrentTimeField;
        
        private bool OpenedField;
        
        private System.DateTime RealDateEndField;
        
        private System.DateTime RealDateStartField;
        
        private string ReviewCommentField;
        
        private bool ReviewedField;
        
        private string SelAuthorField;
        
        private string StateField;
        
        private string StateDBField;
        
        private string StropUserField;
        
        private string StropUserShortField;
        
        private VotGESOrders.CranService.CranTaskAction TaskActionField;
        
        private VotGESOrders.CranService.CranTaskState TaskStateField;
        
        private int YearNumberField;
        
        private bool canCancelField;
        
        private bool canChangeField;
        
        private bool canCheckField;
        
        private bool canCommentField;
        
        private bool canFinishField;
        
        private bool canOpenField;
        
        private bool canReturnField;
        
        private bool changeField;
        
        private bool changedField;
        
        private bool checkField;
        
        private string crossTasksField;
        
        private bool hasCrossTasksField;
        
        private bool initField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AgreeComments {
            get {
                return this.AgreeCommentsField;
            }
            set {
                if ((object.ReferenceEquals(this.AgreeCommentsField, value) != true)) {
                    this.AgreeCommentsField = value;
                    this.RaisePropertyChanged("AgreeComments");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.Dictionary<int, string> AgreeDict {
            get {
                return this.AgreeDictField;
            }
            set {
                if ((object.ReferenceEquals(this.AgreeDictField, value) != true)) {
                    this.AgreeDictField = value;
                    this.RaisePropertyChanged("AgreeDict");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime AllowDateEnd {
            get {
                return this.AllowDateEndField;
            }
            set {
                if ((this.AllowDateEndField.Equals(value) != true)) {
                    this.AllowDateEndField = value;
                    this.RaisePropertyChanged("AllowDateEnd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime AllowDateStart {
            get {
                return this.AllowDateStartField;
            }
            set {
                if ((this.AllowDateStartField.Equals(value) != true)) {
                    this.AllowDateStartField = value;
                    this.RaisePropertyChanged("AllowDateStart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Allowed {
            get {
                return this.AllowedField;
            }
            set {
                if ((this.AllowedField.Equals(value) != true)) {
                    this.AllowedField = value;
                    this.RaisePropertyChanged("Allowed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Author {
            get {
                return this.AuthorField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorField, value) != true)) {
                    this.AuthorField = value;
                    this.RaisePropertyChanged("Author");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AuthorAllow {
            get {
                return this.AuthorAllowField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorAllowField, value) != true)) {
                    this.AuthorAllowField = value;
                    this.RaisePropertyChanged("AuthorAllow");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AuthorCancel {
            get {
                return this.AuthorCancelField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorCancelField, value) != true)) {
                    this.AuthorCancelField = value;
                    this.RaisePropertyChanged("AuthorCancel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AuthorFinish {
            get {
                return this.AuthorFinishField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorFinishField, value) != true)) {
                    this.AuthorFinishField = value;
                    this.RaisePropertyChanged("AuthorFinish");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AuthorOpen {
            get {
                return this.AuthorOpenField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorOpenField, value) != true)) {
                    this.AuthorOpenField = value;
                    this.RaisePropertyChanged("AuthorOpen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string AuthorText {
            get {
                return this.AuthorTextField;
            }
            set {
                if ((object.ReferenceEquals(this.AuthorTextField, value) != true)) {
                    this.AuthorTextField = value;
                    this.RaisePropertyChanged("AuthorText");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Cancelled {
            get {
                return this.CancelledField;
            }
            set {
                if ((this.CancelledField.Equals(value) != true)) {
                    this.CancelledField = value;
                    this.RaisePropertyChanged("Cancelled");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Comment {
            get {
                return this.CommentField;
            }
            set {
                if ((object.ReferenceEquals(this.CommentField, value) != true)) {
                    this.CommentField = value;
                    this.RaisePropertyChanged("Comment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CranName {
            get {
                return this.CranNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CranNameField, value) != true)) {
                    this.CranNameField = value;
                    this.RaisePropertyChanged("CranName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CranNumber {
            get {
                return this.CranNumberField;
            }
            set {
                if ((this.CranNumberField.Equals(value) != true)) {
                    this.CranNumberField = value;
                    this.RaisePropertyChanged("CranNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CranUser {
            get {
                return this.CranUserField;
            }
            set {
                if ((object.ReferenceEquals(this.CranUserField, value) != true)) {
                    this.CranUserField = value;
                    this.RaisePropertyChanged("CranUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CranUserShort {
            get {
                return this.CranUserShortField;
            }
            set {
                if ((object.ReferenceEquals(this.CranUserShortField, value) != true)) {
                    this.CranUserShortField = value;
                    this.RaisePropertyChanged("CranUserShort");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateCreate {
            get {
                return this.DateCreateField;
            }
            set {
                if ((this.DateCreateField.Equals(value) != true)) {
                    this.DateCreateField = value;
                    this.RaisePropertyChanged("DateCreate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Denied {
            get {
                return this.DeniedField;
            }
            set {
                if ((this.DeniedField.Equals(value) != true)) {
                    this.DeniedField = value;
                    this.RaisePropertyChanged("Denied");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool FinishCurrentTime {
            get {
                return this.FinishCurrentTimeField;
            }
            set {
                if ((this.FinishCurrentTimeField.Equals(value) != true)) {
                    this.FinishCurrentTimeField = value;
                    this.RaisePropertyChanged("FinishCurrentTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Finished {
            get {
                return this.FinishedField;
            }
            set {
                if ((this.FinishedField.Equals(value) != true)) {
                    this.FinishedField = value;
                    this.RaisePropertyChanged("Finished");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasAgreeComment {
            get {
                return this.HasAgreeCommentField;
            }
            set {
                if ((this.HasAgreeCommentField.Equals(value) != true)) {
                    this.HasAgreeCommentField = value;
                    this.RaisePropertyChanged("HasAgreeComment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool HasReviewComment {
            get {
                return this.HasReviewCommentField;
            }
            set {
                if ((this.HasReviewCommentField.Equals(value) != true)) {
                    this.HasReviewCommentField = value;
                    this.RaisePropertyChanged("HasReviewComment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Manager {
            get {
                return this.ManagerField;
            }
            set {
                if ((object.ReferenceEquals(this.ManagerField, value) != true)) {
                    this.ManagerField = value;
                    this.RaisePropertyChanged("Manager");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ManagerShort {
            get {
                return this.ManagerShortField;
            }
            set {
                if ((object.ReferenceEquals(this.ManagerShortField, value) != true)) {
                    this.ManagerShortField = value;
                    this.RaisePropertyChanged("ManagerShort");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime NeedEndDate {
            get {
                return this.NeedEndDateField;
            }
            set {
                if ((this.NeedEndDateField.Equals(value) != true)) {
                    this.NeedEndDateField = value;
                    this.RaisePropertyChanged("NeedEndDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime NeedStartDate {
            get {
                return this.NeedStartDateField;
            }
            set {
                if ((this.NeedStartDateField.Equals(value) != true)) {
                    this.NeedStartDateField = value;
                    this.RaisePropertyChanged("NeedStartDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Number {
            get {
                return this.NumberField;
            }
            set {
                if ((this.NumberField.Equals(value) != true)) {
                    this.NumberField = value;
                    this.RaisePropertyChanged("Number");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool OpenCurrentTime {
            get {
                return this.OpenCurrentTimeField;
            }
            set {
                if ((this.OpenCurrentTimeField.Equals(value) != true)) {
                    this.OpenCurrentTimeField = value;
                    this.RaisePropertyChanged("OpenCurrentTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Opened {
            get {
                return this.OpenedField;
            }
            set {
                if ((this.OpenedField.Equals(value) != true)) {
                    this.OpenedField = value;
                    this.RaisePropertyChanged("Opened");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RealDateEnd {
            get {
                return this.RealDateEndField;
            }
            set {
                if ((this.RealDateEndField.Equals(value) != true)) {
                    this.RealDateEndField = value;
                    this.RaisePropertyChanged("RealDateEnd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime RealDateStart {
            get {
                return this.RealDateStartField;
            }
            set {
                if ((this.RealDateStartField.Equals(value) != true)) {
                    this.RealDateStartField = value;
                    this.RaisePropertyChanged("RealDateStart");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ReviewComment {
            get {
                return this.ReviewCommentField;
            }
            set {
                if ((object.ReferenceEquals(this.ReviewCommentField, value) != true)) {
                    this.ReviewCommentField = value;
                    this.RaisePropertyChanged("ReviewComment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Reviewed {
            get {
                return this.ReviewedField;
            }
            set {
                if ((this.ReviewedField.Equals(value) != true)) {
                    this.ReviewedField = value;
                    this.RaisePropertyChanged("Reviewed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SelAuthor {
            get {
                return this.SelAuthorField;
            }
            set {
                if ((object.ReferenceEquals(this.SelAuthorField, value) != true)) {
                    this.SelAuthorField = value;
                    this.RaisePropertyChanged("SelAuthor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StateDB {
            get {
                return this.StateDBField;
            }
            set {
                if ((object.ReferenceEquals(this.StateDBField, value) != true)) {
                    this.StateDBField = value;
                    this.RaisePropertyChanged("StateDB");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StropUser {
            get {
                return this.StropUserField;
            }
            set {
                if ((object.ReferenceEquals(this.StropUserField, value) != true)) {
                    this.StropUserField = value;
                    this.RaisePropertyChanged("StropUser");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StropUserShort {
            get {
                return this.StropUserShortField;
            }
            set {
                if ((object.ReferenceEquals(this.StropUserShortField, value) != true)) {
                    this.StropUserShortField = value;
                    this.RaisePropertyChanged("StropUserShort");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VotGESOrders.CranService.CranTaskAction TaskAction {
            get {
                return this.TaskActionField;
            }
            set {
                if ((this.TaskActionField.Equals(value) != true)) {
                    this.TaskActionField = value;
                    this.RaisePropertyChanged("TaskAction");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public VotGESOrders.CranService.CranTaskState TaskState {
            get {
                return this.TaskStateField;
            }
            set {
                if ((this.TaskStateField.Equals(value) != true)) {
                    this.TaskStateField = value;
                    this.RaisePropertyChanged("TaskState");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int YearNumber {
            get {
                return this.YearNumberField;
            }
            set {
                if ((this.YearNumberField.Equals(value) != true)) {
                    this.YearNumberField = value;
                    this.RaisePropertyChanged("YearNumber");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool canCancel {
            get {
                return this.canCancelField;
            }
            set {
                if ((this.canCancelField.Equals(value) != true)) {
                    this.canCancelField = value;
                    this.RaisePropertyChanged("canCancel");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool canChange {
            get {
                return this.canChangeField;
            }
            set {
                if ((this.canChangeField.Equals(value) != true)) {
                    this.canChangeField = value;
                    this.RaisePropertyChanged("canChange");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool canCheck {
            get {
                return this.canCheckField;
            }
            set {
                if ((this.canCheckField.Equals(value) != true)) {
                    this.canCheckField = value;
                    this.RaisePropertyChanged("canCheck");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool canComment {
            get {
                return this.canCommentField;
            }
            set {
                if ((this.canCommentField.Equals(value) != true)) {
                    this.canCommentField = value;
                    this.RaisePropertyChanged("canComment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool canFinish {
            get {
                return this.canFinishField;
            }
            set {
                if ((this.canFinishField.Equals(value) != true)) {
                    this.canFinishField = value;
                    this.RaisePropertyChanged("canFinish");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool canOpen {
            get {
                return this.canOpenField;
            }
            set {
                if ((this.canOpenField.Equals(value) != true)) {
                    this.canOpenField = value;
                    this.RaisePropertyChanged("canOpen");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool canReturn {
            get {
                return this.canReturnField;
            }
            set {
                if ((this.canReturnField.Equals(value) != true)) {
                    this.canReturnField = value;
                    this.RaisePropertyChanged("canReturn");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool change {
            get {
                return this.changeField;
            }
            set {
                if ((this.changeField.Equals(value) != true)) {
                    this.changeField = value;
                    this.RaisePropertyChanged("change");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool changed {
            get {
                return this.changedField;
            }
            set {
                if ((this.changedField.Equals(value) != true)) {
                    this.changedField = value;
                    this.RaisePropertyChanged("changed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool check {
            get {
                return this.checkField;
            }
            set {
                if ((this.checkField.Equals(value) != true)) {
                    this.checkField = value;
                    this.RaisePropertyChanged("check");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string crossTasks {
            get {
                return this.crossTasksField;
            }
            set {
                if ((object.ReferenceEquals(this.crossTasksField, value) != true)) {
                    this.crossTasksField = value;
                    this.RaisePropertyChanged("crossTasks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool hasCrossTasks {
            get {
                return this.hasCrossTasksField;
            }
            set {
                if ((this.hasCrossTasksField.Equals(value) != true)) {
                    this.hasCrossTasksField = value;
                    this.RaisePropertyChanged("hasCrossTasks");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool init {
            get {
                return this.initField;
            }
            set {
                if ((this.initField.Equals(value) != true)) {
                    this.initField = value;
                    this.RaisePropertyChanged("init");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CranTaskAction", Namespace="http://schemas.datacontract.org/2004/07/VotGESOrders.Web.Models")]
    public enum CranTaskAction : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        none = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        create = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        change = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        review = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        open = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        finish = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        cancel = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        returnCancel = 7,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CranTaskState", Namespace="http://schemas.datacontract.org/2004/07/VotGESOrders.Web.Models")]
    public enum CranTaskState : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        created = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        reviewed = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        canceled = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        opened = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        finished = 4,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ReturnMessage", Namespace="http://schemas.datacontract.org/2004/07/VotGESOrders.Web.Models")]
    public partial class ReturnMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string MessageField;
        
        private bool ResultField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="CranService.CranService")]
    public interface CranService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:CranService/DoWork", ReplyAction="urn:CranService/DoWorkResponse")]
        System.IAsyncResult BeginDoWork(System.AsyncCallback callback, object asyncState);
        
        void EndDoWork(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:CranService/getCranTasks", ReplyAction="urn:CranService/getCranTasksResponse")]
        System.IAsyncResult BegingetCranTasks(VotGESOrders.CranService.CranFilter Filter, System.AsyncCallback callback, object asyncState);
        
        VotGESOrders.CranService.CranFilter EndgetCranTasks(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:CranService/CreateCranTask", ReplyAction="urn:CranService/CreateCranTaskResponse")]
        System.IAsyncResult BeginCreateCranTask(VotGESOrders.CranService.CranTaskInfo task, System.AsyncCallback callback, object asyncState);
        
        VotGESOrders.CranService.ReturnMessage EndCreateCranTask(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:CranService/CommentCranTask", ReplyAction="urn:CranService/CommentCranTaskResponse")]
        System.IAsyncResult BeginCommentCranTask(VotGESOrders.CranService.CranTaskInfo task, string comment, System.AsyncCallback callback, object asyncState);
        
        VotGESOrders.CranService.ReturnMessage EndCommentCranTask(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:CranService/CancelCranTask", ReplyAction="urn:CranService/CancelCranTaskResponse")]
        System.IAsyncResult BeginCancelCranTask(VotGESOrders.CranService.CranTaskInfo task, System.AsyncCallback callback, object asyncState);
        
        VotGESOrders.CranService.ReturnMessage EndCancelCranTask(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:CranService/FinishCranTask", ReplyAction="urn:CranService/FinishCranTaskResponse")]
        System.IAsyncResult BeginFinishCranTask(VotGESOrders.CranService.CranTaskInfo task, System.AsyncCallback callback, object asyncState);
        
        VotGESOrders.CranService.ReturnMessage EndFinishCranTask(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:CranService/getLastUpdate", ReplyAction="urn:CranService/getLastUpdateResponse")]
        System.IAsyncResult BegingetLastUpdate(System.AsyncCallback callback, object asyncState);
        
        System.DateTime EndgetLastUpdate(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CranServiceChannel : VotGESOrders.CranService.CranService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getCranTasksCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getCranTasksCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public VotGESOrders.CranService.CranFilter Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((VotGESOrders.CranService.CranFilter)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CreateCranTaskCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public CreateCranTaskCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public VotGESOrders.CranService.ReturnMessage Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((VotGESOrders.CranService.ReturnMessage)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CommentCranTaskCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public CommentCranTaskCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public VotGESOrders.CranService.ReturnMessage Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((VotGESOrders.CranService.ReturnMessage)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CancelCranTaskCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public CancelCranTaskCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public VotGESOrders.CranService.ReturnMessage Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((VotGESOrders.CranService.ReturnMessage)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FinishCranTaskCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public FinishCranTaskCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public VotGESOrders.CranService.ReturnMessage Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((VotGESOrders.CranService.ReturnMessage)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class getLastUpdateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public getLastUpdateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.DateTime Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.DateTime)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CranServiceClient : System.ServiceModel.ClientBase<VotGESOrders.CranService.CranService>, VotGESOrders.CranService.CranService {
        
        private BeginOperationDelegate onBeginDoWorkDelegate;
        
        private EndOperationDelegate onEndDoWorkDelegate;
        
        private System.Threading.SendOrPostCallback onDoWorkCompletedDelegate;
        
        private BeginOperationDelegate onBegingetCranTasksDelegate;
        
        private EndOperationDelegate onEndgetCranTasksDelegate;
        
        private System.Threading.SendOrPostCallback ongetCranTasksCompletedDelegate;
        
        private BeginOperationDelegate onBeginCreateCranTaskDelegate;
        
        private EndOperationDelegate onEndCreateCranTaskDelegate;
        
        private System.Threading.SendOrPostCallback onCreateCranTaskCompletedDelegate;
        
        private BeginOperationDelegate onBeginCommentCranTaskDelegate;
        
        private EndOperationDelegate onEndCommentCranTaskDelegate;
        
        private System.Threading.SendOrPostCallback onCommentCranTaskCompletedDelegate;
        
        private BeginOperationDelegate onBeginCancelCranTaskDelegate;
        
        private EndOperationDelegate onEndCancelCranTaskDelegate;
        
        private System.Threading.SendOrPostCallback onCancelCranTaskCompletedDelegate;
        
        private BeginOperationDelegate onBeginFinishCranTaskDelegate;
        
        private EndOperationDelegate onEndFinishCranTaskDelegate;
        
        private System.Threading.SendOrPostCallback onFinishCranTaskCompletedDelegate;
        
        private BeginOperationDelegate onBegingetLastUpdateDelegate;
        
        private EndOperationDelegate onEndgetLastUpdateDelegate;
        
        private System.Threading.SendOrPostCallback ongetLastUpdateCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public CranServiceClient() {
        }
        
        public CranServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CranServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CranServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CranServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Не удалось установить CookieContainer. Убедитесь, что привязка содержит HttpCooki" +
                            "eContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> DoWorkCompleted;
        
        public event System.EventHandler<getCranTasksCompletedEventArgs> getCranTasksCompleted;
        
        public event System.EventHandler<CreateCranTaskCompletedEventArgs> CreateCranTaskCompleted;
        
        public event System.EventHandler<CommentCranTaskCompletedEventArgs> CommentCranTaskCompleted;
        
        public event System.EventHandler<CancelCranTaskCompletedEventArgs> CancelCranTaskCompleted;
        
        public event System.EventHandler<FinishCranTaskCompletedEventArgs> FinishCranTaskCompleted;
        
        public event System.EventHandler<getLastUpdateCompletedEventArgs> getLastUpdateCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult VotGESOrders.CranService.CranService.BeginDoWork(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDoWork(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void VotGESOrders.CranService.CranService.EndDoWork(System.IAsyncResult result) {
            base.Channel.EndDoWork(result);
        }
        
        private System.IAsyncResult OnBeginDoWork(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((VotGESOrders.CranService.CranService)(this)).BeginDoWork(callback, asyncState);
        }
        
        private object[] OnEndDoWork(System.IAsyncResult result) {
            ((VotGESOrders.CranService.CranService)(this)).EndDoWork(result);
            return null;
        }
        
        private void OnDoWorkCompleted(object state) {
            if ((this.DoWorkCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DoWorkCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DoWorkAsync() {
            this.DoWorkAsync(null);
        }
        
        public void DoWorkAsync(object userState) {
            if ((this.onBeginDoWorkDelegate == null)) {
                this.onBeginDoWorkDelegate = new BeginOperationDelegate(this.OnBeginDoWork);
            }
            if ((this.onEndDoWorkDelegate == null)) {
                this.onEndDoWorkDelegate = new EndOperationDelegate(this.OnEndDoWork);
            }
            if ((this.onDoWorkCompletedDelegate == null)) {
                this.onDoWorkCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDoWorkCompleted);
            }
            base.InvokeAsync(this.onBeginDoWorkDelegate, null, this.onEndDoWorkDelegate, this.onDoWorkCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult VotGESOrders.CranService.CranService.BegingetCranTasks(VotGESOrders.CranService.CranFilter Filter, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetCranTasks(Filter, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VotGESOrders.CranService.CranFilter VotGESOrders.CranService.CranService.EndgetCranTasks(System.IAsyncResult result) {
            return base.Channel.EndgetCranTasks(result);
        }
        
        private System.IAsyncResult OnBegingetCranTasks(object[] inValues, System.AsyncCallback callback, object asyncState) {
            VotGESOrders.CranService.CranFilter Filter = ((VotGESOrders.CranService.CranFilter)(inValues[0]));
            return ((VotGESOrders.CranService.CranService)(this)).BegingetCranTasks(Filter, callback, asyncState);
        }
        
        private object[] OnEndgetCranTasks(System.IAsyncResult result) {
            VotGESOrders.CranService.CranFilter retVal = ((VotGESOrders.CranService.CranService)(this)).EndgetCranTasks(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetCranTasksCompleted(object state) {
            if ((this.getCranTasksCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getCranTasksCompleted(this, new getCranTasksCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getCranTasksAsync(VotGESOrders.CranService.CranFilter Filter) {
            this.getCranTasksAsync(Filter, null);
        }
        
        public void getCranTasksAsync(VotGESOrders.CranService.CranFilter Filter, object userState) {
            if ((this.onBegingetCranTasksDelegate == null)) {
                this.onBegingetCranTasksDelegate = new BeginOperationDelegate(this.OnBegingetCranTasks);
            }
            if ((this.onEndgetCranTasksDelegate == null)) {
                this.onEndgetCranTasksDelegate = new EndOperationDelegate(this.OnEndgetCranTasks);
            }
            if ((this.ongetCranTasksCompletedDelegate == null)) {
                this.ongetCranTasksCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetCranTasksCompleted);
            }
            base.InvokeAsync(this.onBegingetCranTasksDelegate, new object[] {
                        Filter}, this.onEndgetCranTasksDelegate, this.ongetCranTasksCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult VotGESOrders.CranService.CranService.BeginCreateCranTask(VotGESOrders.CranService.CranTaskInfo task, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginCreateCranTask(task, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VotGESOrders.CranService.ReturnMessage VotGESOrders.CranService.CranService.EndCreateCranTask(System.IAsyncResult result) {
            return base.Channel.EndCreateCranTask(result);
        }
        
        private System.IAsyncResult OnBeginCreateCranTask(object[] inValues, System.AsyncCallback callback, object asyncState) {
            VotGESOrders.CranService.CranTaskInfo task = ((VotGESOrders.CranService.CranTaskInfo)(inValues[0]));
            return ((VotGESOrders.CranService.CranService)(this)).BeginCreateCranTask(task, callback, asyncState);
        }
        
        private object[] OnEndCreateCranTask(System.IAsyncResult result) {
            VotGESOrders.CranService.ReturnMessage retVal = ((VotGESOrders.CranService.CranService)(this)).EndCreateCranTask(result);
            return new object[] {
                    retVal};
        }
        
        private void OnCreateCranTaskCompleted(object state) {
            if ((this.CreateCranTaskCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CreateCranTaskCompleted(this, new CreateCranTaskCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CreateCranTaskAsync(VotGESOrders.CranService.CranTaskInfo task) {
            this.CreateCranTaskAsync(task, null);
        }
        
        public void CreateCranTaskAsync(VotGESOrders.CranService.CranTaskInfo task, object userState) {
            if ((this.onBeginCreateCranTaskDelegate == null)) {
                this.onBeginCreateCranTaskDelegate = new BeginOperationDelegate(this.OnBeginCreateCranTask);
            }
            if ((this.onEndCreateCranTaskDelegate == null)) {
                this.onEndCreateCranTaskDelegate = new EndOperationDelegate(this.OnEndCreateCranTask);
            }
            if ((this.onCreateCranTaskCompletedDelegate == null)) {
                this.onCreateCranTaskCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCreateCranTaskCompleted);
            }
            base.InvokeAsync(this.onBeginCreateCranTaskDelegate, new object[] {
                        task}, this.onEndCreateCranTaskDelegate, this.onCreateCranTaskCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult VotGESOrders.CranService.CranService.BeginCommentCranTask(VotGESOrders.CranService.CranTaskInfo task, string comment, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginCommentCranTask(task, comment, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VotGESOrders.CranService.ReturnMessage VotGESOrders.CranService.CranService.EndCommentCranTask(System.IAsyncResult result) {
            return base.Channel.EndCommentCranTask(result);
        }
        
        private System.IAsyncResult OnBeginCommentCranTask(object[] inValues, System.AsyncCallback callback, object asyncState) {
            VotGESOrders.CranService.CranTaskInfo task = ((VotGESOrders.CranService.CranTaskInfo)(inValues[0]));
            string comment = ((string)(inValues[1]));
            return ((VotGESOrders.CranService.CranService)(this)).BeginCommentCranTask(task, comment, callback, asyncState);
        }
        
        private object[] OnEndCommentCranTask(System.IAsyncResult result) {
            VotGESOrders.CranService.ReturnMessage retVal = ((VotGESOrders.CranService.CranService)(this)).EndCommentCranTask(result);
            return new object[] {
                    retVal};
        }
        
        private void OnCommentCranTaskCompleted(object state) {
            if ((this.CommentCranTaskCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CommentCranTaskCompleted(this, new CommentCranTaskCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CommentCranTaskAsync(VotGESOrders.CranService.CranTaskInfo task, string comment) {
            this.CommentCranTaskAsync(task, comment, null);
        }
        
        public void CommentCranTaskAsync(VotGESOrders.CranService.CranTaskInfo task, string comment, object userState) {
            if ((this.onBeginCommentCranTaskDelegate == null)) {
                this.onBeginCommentCranTaskDelegate = new BeginOperationDelegate(this.OnBeginCommentCranTask);
            }
            if ((this.onEndCommentCranTaskDelegate == null)) {
                this.onEndCommentCranTaskDelegate = new EndOperationDelegate(this.OnEndCommentCranTask);
            }
            if ((this.onCommentCranTaskCompletedDelegate == null)) {
                this.onCommentCranTaskCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCommentCranTaskCompleted);
            }
            base.InvokeAsync(this.onBeginCommentCranTaskDelegate, new object[] {
                        task,
                        comment}, this.onEndCommentCranTaskDelegate, this.onCommentCranTaskCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult VotGESOrders.CranService.CranService.BeginCancelCranTask(VotGESOrders.CranService.CranTaskInfo task, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginCancelCranTask(task, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VotGESOrders.CranService.ReturnMessage VotGESOrders.CranService.CranService.EndCancelCranTask(System.IAsyncResult result) {
            return base.Channel.EndCancelCranTask(result);
        }
        
        private System.IAsyncResult OnBeginCancelCranTask(object[] inValues, System.AsyncCallback callback, object asyncState) {
            VotGESOrders.CranService.CranTaskInfo task = ((VotGESOrders.CranService.CranTaskInfo)(inValues[0]));
            return ((VotGESOrders.CranService.CranService)(this)).BeginCancelCranTask(task, callback, asyncState);
        }
        
        private object[] OnEndCancelCranTask(System.IAsyncResult result) {
            VotGESOrders.CranService.ReturnMessage retVal = ((VotGESOrders.CranService.CranService)(this)).EndCancelCranTask(result);
            return new object[] {
                    retVal};
        }
        
        private void OnCancelCranTaskCompleted(object state) {
            if ((this.CancelCranTaskCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CancelCranTaskCompleted(this, new CancelCranTaskCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CancelCranTaskAsync(VotGESOrders.CranService.CranTaskInfo task) {
            this.CancelCranTaskAsync(task, null);
        }
        
        public void CancelCranTaskAsync(VotGESOrders.CranService.CranTaskInfo task, object userState) {
            if ((this.onBeginCancelCranTaskDelegate == null)) {
                this.onBeginCancelCranTaskDelegate = new BeginOperationDelegate(this.OnBeginCancelCranTask);
            }
            if ((this.onEndCancelCranTaskDelegate == null)) {
                this.onEndCancelCranTaskDelegate = new EndOperationDelegate(this.OnEndCancelCranTask);
            }
            if ((this.onCancelCranTaskCompletedDelegate == null)) {
                this.onCancelCranTaskCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCancelCranTaskCompleted);
            }
            base.InvokeAsync(this.onBeginCancelCranTaskDelegate, new object[] {
                        task}, this.onEndCancelCranTaskDelegate, this.onCancelCranTaskCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult VotGESOrders.CranService.CranService.BeginFinishCranTask(VotGESOrders.CranService.CranTaskInfo task, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginFinishCranTask(task, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        VotGESOrders.CranService.ReturnMessage VotGESOrders.CranService.CranService.EndFinishCranTask(System.IAsyncResult result) {
            return base.Channel.EndFinishCranTask(result);
        }
        
        private System.IAsyncResult OnBeginFinishCranTask(object[] inValues, System.AsyncCallback callback, object asyncState) {
            VotGESOrders.CranService.CranTaskInfo task = ((VotGESOrders.CranService.CranTaskInfo)(inValues[0]));
            return ((VotGESOrders.CranService.CranService)(this)).BeginFinishCranTask(task, callback, asyncState);
        }
        
        private object[] OnEndFinishCranTask(System.IAsyncResult result) {
            VotGESOrders.CranService.ReturnMessage retVal = ((VotGESOrders.CranService.CranService)(this)).EndFinishCranTask(result);
            return new object[] {
                    retVal};
        }
        
        private void OnFinishCranTaskCompleted(object state) {
            if ((this.FinishCranTaskCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.FinishCranTaskCompleted(this, new FinishCranTaskCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void FinishCranTaskAsync(VotGESOrders.CranService.CranTaskInfo task) {
            this.FinishCranTaskAsync(task, null);
        }
        
        public void FinishCranTaskAsync(VotGESOrders.CranService.CranTaskInfo task, object userState) {
            if ((this.onBeginFinishCranTaskDelegate == null)) {
                this.onBeginFinishCranTaskDelegate = new BeginOperationDelegate(this.OnBeginFinishCranTask);
            }
            if ((this.onEndFinishCranTaskDelegate == null)) {
                this.onEndFinishCranTaskDelegate = new EndOperationDelegate(this.OnEndFinishCranTask);
            }
            if ((this.onFinishCranTaskCompletedDelegate == null)) {
                this.onFinishCranTaskCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnFinishCranTaskCompleted);
            }
            base.InvokeAsync(this.onBeginFinishCranTaskDelegate, new object[] {
                        task}, this.onEndFinishCranTaskDelegate, this.onFinishCranTaskCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult VotGESOrders.CranService.CranService.BegingetLastUpdate(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BegingetLastUpdate(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.DateTime VotGESOrders.CranService.CranService.EndgetLastUpdate(System.IAsyncResult result) {
            return base.Channel.EndgetLastUpdate(result);
        }
        
        private System.IAsyncResult OnBegingetLastUpdate(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((VotGESOrders.CranService.CranService)(this)).BegingetLastUpdate(callback, asyncState);
        }
        
        private object[] OnEndgetLastUpdate(System.IAsyncResult result) {
            System.DateTime retVal = ((VotGESOrders.CranService.CranService)(this)).EndgetLastUpdate(result);
            return new object[] {
                    retVal};
        }
        
        private void OngetLastUpdateCompleted(object state) {
            if ((this.getLastUpdateCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.getLastUpdateCompleted(this, new getLastUpdateCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void getLastUpdateAsync() {
            this.getLastUpdateAsync(null);
        }
        
        public void getLastUpdateAsync(object userState) {
            if ((this.onBegingetLastUpdateDelegate == null)) {
                this.onBegingetLastUpdateDelegate = new BeginOperationDelegate(this.OnBegingetLastUpdate);
            }
            if ((this.onEndgetLastUpdateDelegate == null)) {
                this.onEndgetLastUpdateDelegate = new EndOperationDelegate(this.OnEndgetLastUpdate);
            }
            if ((this.ongetLastUpdateCompletedDelegate == null)) {
                this.ongetLastUpdateCompletedDelegate = new System.Threading.SendOrPostCallback(this.OngetLastUpdateCompleted);
            }
            base.InvokeAsync(this.onBegingetLastUpdateDelegate, null, this.onEndgetLastUpdateDelegate, this.ongetLastUpdateCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override VotGESOrders.CranService.CranService CreateChannel() {
            return new CranServiceClientChannel(this);
        }
        
        private class CranServiceClientChannel : ChannelBase<VotGESOrders.CranService.CranService>, VotGESOrders.CranService.CranService {
            
            public CranServiceClientChannel(System.ServiceModel.ClientBase<VotGESOrders.CranService.CranService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginDoWork(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("DoWork", _args, callback, asyncState);
                return _result;
            }
            
            public void EndDoWork(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("DoWork", _args, result);
            }
            
            public System.IAsyncResult BegingetCranTasks(VotGESOrders.CranService.CranFilter Filter, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = Filter;
                System.IAsyncResult _result = base.BeginInvoke("getCranTasks", _args, callback, asyncState);
                return _result;
            }
            
            public VotGESOrders.CranService.CranFilter EndgetCranTasks(System.IAsyncResult result) {
                object[] _args = new object[0];
                VotGESOrders.CranService.CranFilter _result = ((VotGESOrders.CranService.CranFilter)(base.EndInvoke("getCranTasks", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginCreateCranTask(VotGESOrders.CranService.CranTaskInfo task, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = task;
                System.IAsyncResult _result = base.BeginInvoke("CreateCranTask", _args, callback, asyncState);
                return _result;
            }
            
            public VotGESOrders.CranService.ReturnMessage EndCreateCranTask(System.IAsyncResult result) {
                object[] _args = new object[0];
                VotGESOrders.CranService.ReturnMessage _result = ((VotGESOrders.CranService.ReturnMessage)(base.EndInvoke("CreateCranTask", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginCommentCranTask(VotGESOrders.CranService.CranTaskInfo task, string comment, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[2];
                _args[0] = task;
                _args[1] = comment;
                System.IAsyncResult _result = base.BeginInvoke("CommentCranTask", _args, callback, asyncState);
                return _result;
            }
            
            public VotGESOrders.CranService.ReturnMessage EndCommentCranTask(System.IAsyncResult result) {
                object[] _args = new object[0];
                VotGESOrders.CranService.ReturnMessage _result = ((VotGESOrders.CranService.ReturnMessage)(base.EndInvoke("CommentCranTask", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginCancelCranTask(VotGESOrders.CranService.CranTaskInfo task, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = task;
                System.IAsyncResult _result = base.BeginInvoke("CancelCranTask", _args, callback, asyncState);
                return _result;
            }
            
            public VotGESOrders.CranService.ReturnMessage EndCancelCranTask(System.IAsyncResult result) {
                object[] _args = new object[0];
                VotGESOrders.CranService.ReturnMessage _result = ((VotGESOrders.CranService.ReturnMessage)(base.EndInvoke("CancelCranTask", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginFinishCranTask(VotGESOrders.CranService.CranTaskInfo task, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = task;
                System.IAsyncResult _result = base.BeginInvoke("FinishCranTask", _args, callback, asyncState);
                return _result;
            }
            
            public VotGESOrders.CranService.ReturnMessage EndFinishCranTask(System.IAsyncResult result) {
                object[] _args = new object[0];
                VotGESOrders.CranService.ReturnMessage _result = ((VotGESOrders.CranService.ReturnMessage)(base.EndInvoke("FinishCranTask", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BegingetLastUpdate(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("getLastUpdate", _args, callback, asyncState);
                return _result;
            }
            
            public System.DateTime EndgetLastUpdate(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.DateTime _result = ((System.DateTime)(base.EndInvoke("getLastUpdate", _args, result)));
                return _result;
            }
        }
    }
}
